export const TODO_LIST_REQUEST = 'TODO_LIST_REQUEST';
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS';
export const TODO_LIST_FAIL = 'TODO_LIST_FAIL';

export const TODO_CREATE_REQUEST = 'TODO_CREATE_REQUEST';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_CREATE_FAIL = 'TODO_CREATE_FAIL';
export const TODO_CREATE_RESET = 'TODO_CREATE_RESET'

export const TODO_BY_ID_REQUEST = 'TODO_BY_ID_REQUEST'
export const TODO_BY_ID_SUCCESS = 'TODO_BY_ID_SUCCESS'
export const TODO_BY_ID_FAIL = 'TODO_BY_ID_FAIL'


